[package]
name = "typst-as-library"
version = "0.2.0"
edition = "2024"

[dependencies]
# typst essentials
typst = "0.13.1"

# utils
typst-kit = "0.13.1"
typst-pdf = "0.13.1"

[lib]
name = "typst_as_library"
